build:
    image: node:6.6
    commands:
        - npm install

publish:
  docker:
    repo: $$DOCKER_USERNAME/compliancebot
    tag: latest
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    file: Dockerfile

deploy:
  webhook:
    image: plugins/drone-webhook
    skip_verify: true
    method: POST
    auth:
      username: $$MANTL_USERNAME
      password: $$MANTL_PASSWORD
    urls:
      - https://$$MANTL_CONTROL/marathon/v2/apps/imapex/sparktrak2/compliancebot/restart?force=true

notify:
  spark:
    image: hpreston/drone-spark
    auth_token: $$SPARK_TOKEN
    roomId: $$SPARK_ROOM
